### ISSUE TITLE
Data OSM

### ISSUE THREAD

**Issue by intocoding** [fom-big-data/fom-big-data-consulting-berlin-mobility-model#7]
### **ToDo**

- [ ] "non Prio" Export Netzwerk - Train/Railway (fehlerhafte Daten, S-Bahn-U-Bahn prüfen!!!!)

- [ ] "non Prio" OSM Tags nutzen (Parkbuchten usw.)

- [x] export tram data as GEOJson (edges and nodes!)

- [ ] **(Bonus not Necessary)** Export Goemetry - Building specialised governant, medikal, police and firework stations

### **FINISHED**

- [x] Export Goemetry - Building specialised retai and commercial

- [x] bicycle data (explore and visualizied)

- [x] retail and commercial places (explore and visualizied)

- [x] tram data (explore and visualizied)

- [x] Tiefere Exploration

**Comment by MichaelSchwabe** [comment]
reactivate this issue when it is Necessary
